version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run:
        name: "create temp directory for artifacts"
        command: |
          mkdir -p /tmp/artifacts
      - run:
        command: |
          go test -coverprofile=c.out
          go tool cover -html=c.out -o coverage.html
          mv coverage.html /tmp/artifacts
      - store_artifacts:
        path: /tmp/artifacts
